# Generated by Django 3.1.3 on 2020-12-20 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
