# Generated by Django 3.1.3 on 2020-12-20 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0004_remove_customer_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Post',
        ),
    ]
