# Generated by Django 3.1.3 on 2020-12-20 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0005_auto_20201220_1429'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Customer',
        ),
    ]
