# Generated by Django 3.1.3 on 2020-12-20 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0007_order_orderitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
