# Generated by Django 3.1.3 on 2020-12-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0011_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
