# Generated by Django 3.1.3 on 2020-12-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0012_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
