# Generated by Django 3.1.3 on 2020-12-24 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0013_customer_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='file',
        ),
    ]
