# Generated by Django 3.1.3 on 2021-02-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0017_auto_20210108_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='order',
        ),
        migrations.AddField(
            model_name='delivery',
            name='email',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
