# Generated by Django 3.2.5 on 2021-08-11 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enroll', '0019_shipping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='country',
        ),
        migrations.AddField(
            model_name='shipping',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
