# Generated by Django 3.2.5 on 2021-08-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0021_auto_20210814_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='Country',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
