# Generated by Django 3.2.5 on 2021-08-14 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0023_remove_delivery_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='Country',
            new_name='email',
        ),
    ]
