# Generated by Django 3.2.5 on 2021-08-14 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0024_rename_country_delivery_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='email',
            new_name='description',
        ),
    ]
