# Generated by Django 3.2.5 on 2021-08-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0025_rename_email_delivery_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='item',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='myimage'),
        ),
    ]
